// Code generated by protoc-gen-plug. DO NOT EDIT.

package example

import (
	fmt "fmt"
	runtime "github.com/elliotmr/plug/pkg/runtime"
	proto "google.golang.org/protobuf/proto"
)

const (
	GetService runtime.Service = 0
	PutService runtime.Service = 1
)

type KV interface {
	Get(key string) ([]byte, error)
	Put(key string, value []byte) error
}

type kvPlugin struct {
	Impl KV
}

func Run(impl KV) error {
	s := &kvPlugin{Impl: impl}
	return runtime.Run(s)
}

func (x *kvPlugin) Link(srv runtime.Service) (proto.Message, runtime.GenPluginMethod, error) {
	switch srv {
	case GetService:
		return &GetRequest{}, x.Get, nil
	case PutService:
		return &PutRequest{}, x.Put, nil
	}
	return nil, nil, fmt.Errorf("unknown service: %d", srv)
}

func (x *kvPlugin) Get(req proto.Message) (proto.Message, error) {
	in, ok := req.(*GetRequest)
	if !ok {
		return nil, fmt.Errorf("invalid request type")
	}
	value, err := x.Impl.Get(in.Key)
	return &GetResponse{Value: value}, err
}

func (x *kvPlugin) Put(req proto.Message) (proto.Message, error) {
	in, ok := req.(*PutRequest)
	if !ok {
		return nil, fmt.Errorf("invalid request type")
	}
	err := x.Impl.Put(in.Key, in.Value)
	return &Empty{}, err
}

type kvHost struct {
	c *runtime.Host
}

func Load(filename string) (KV, error) {
	c, err := runtime.Load(filename)
	if err != nil {
		return nil, fmt.Errorf("unable to load plugin: %w", err)
	}
	return &kvHost{c: c}, nil
}

func (x *kvHost) Get(key string) ([]byte, error) {
	resp := &GetResponse{}
	err := x.c.SendRecv(GetService, &GetRequest{Key: key}, resp)
	return resp.Value, err
}

func (x *kvHost) Put(key string, value []byte) error {
	resp := &Empty{}
	err := x.c.SendRecv(PutService, &PutRequest{Key: key, Value: value}, resp)
	return err
}

func Test(impl KV) (KV, error) {
	s := &kvPlugin{Impl: impl}
	c, err := runtime.Test(s)
	if err != nil {
		return nil, fmt.Errorf("unable to load plugin: %w", err)
	}
	return &kvHost{c: c}, nil
}
